In [81]:
import pandas as pd

In [92]:
df = pd.read_csv(r"C:\Users\User\Downloads\customer_shopping_data.csv")
df

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall
0,I138884,C241288,Female,28,Clothing,5,1500.40,Credit Card,5/8/2022,Kanyon
1,I317333,C111565,Male,21,Shoes,3,1800.51,Debit Card,12/12/2021,Forum Istanbul
2,I127801,C266599,Male,20,Clothing,1,300.08,Cash,9/11/2021,Metrocity
3,I173702,C988172,Female,66,Shoes,5,3000.85,Credit Card,16/05/2021,Metropol AVM
4,I337046,C189076,Female,53,Books,4,60.60,Cash,24/10/2021,Kanyon
...,...,...,...,...,...,...,...,...,...,...
99452,I219422,C441542,Female,45,Souvenir,5,58.65,Credit Card,21/09/2022,Kanyon
99453,I325143,C569580,Male,27,Food & Beverage,2,10.46,Cash,22/09/2021,Forum Istanbul
99454,I824010,C103292,Male,63,Food & Beverage,2,10.46,Debit Card,28/03/2021,Metrocity
99455,I702964,C800631,Male,56,Technology,4,4200.00,Cash,16/03/2021,Istinye Park
99456,I232867,C273973,Female,36,Souvenir,3,35.19,Credit Card,15/10/2022,Mall of Istanbul

In [93]:
df.isnull().sum()

invoice_no        0
customer_id       0
gender            0
age               0
category          0
quantity          0
price             0
payment_method    0
invoice_date      0
shopping_mall     0
dtype: int64

In [94]:
df.duplicated().sum()

np.int64(0)

In [95]:
df.dtypes

invoice_no         object
customer_id        object
gender             object
age                 int64
category           object
quantity            int64
price             float64
payment_method     object
invoice_date       object
shopping_mall      object
dtype: object

In [88]:
df['invoice_date']= pd.to_datetime(df['invoice_date'], errors = 'coerce')

In [89]:
df.isnull().sum()

invoice_no            0
customer_id           0
gender                0
age                   0
category              0
quantity              0
price                 0
payment_method        0
invoice_date      59428
shopping_mall         0
dtype: int64

In [96]:
df['invoice_date']= pd.to_datetime(df['invoice_date'], format='%d/%m/%Y')

format='%d/%m/%Y
learned this from AI as after changing the pd.to date time it was having null values so took help from AI to solve this problem.

In [97]:
df.isnull().sum()

invoice_no        0
customer_id       0
gender            0
age               0
category          0
quantity          0
price             0
payment_method    0
invoice_date      0
shopping_mall     0
dtype: int64

In [98]:
df.head()

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall
0,I138884,C241288,Female,28,Clothing,5,1500.40,Credit Card,2022-08-05,Kanyon
1,I317333,C111565,Male,21,Shoes,3,1800.51,Debit Card,2021-12-12,Forum Istanbul
2,I127801,C266599,Male,20,Clothing,1,300.08,Cash,2021-11-09,Metrocity
3,I173702,C988172,Female,66,Shoes,5,3000.85,Credit Card,2021-05-16,Metropol AVM
4,I337046,C189076,Female,53,Books,4,60.60,Cash,2021-10-24,Kanyon



                                        ANS NUMBER 1 STARTS FROM HERE

In [99]:
df.groupby(['customer_id','category','gender'])[['price']].sum().head()

                                      price
customer_id category        gender
C100004     Clothing        Male    1500.40
C100005     Shoes           Male    1200.34
C100006     Toys            Male     107.52
C100012     Food & Beverage Male      26.15
C100019     Toys            Female    35.84

In [100]:
df['customer_total_spendeing'] = df['quantity'] * df['price']

In [150]:
most_valuable_customers = df.groupby(['customer_id','category'])[['customer_total_spendeing']].sum()
most_valuable_customers.sort_values(by ='customer_total_spendeing' , ascending = False).head()

                        customer_total_spendeing
customer_id category
C137763     Technology                   26250.0
C699580     Technology                   26250.0
C110600     Technology                   26250.0
C110625     Technology                   26250.0
C211345     Technology                   26250.0

In [152]:
def categoryfx(x):
    if x<5000:
        return('budget')
    elif x<15000:
        return('regular')
    else:
        return('premium')
df['category_new'] = df['customer_total_spendeing'].apply(categoryfx)

In [153]:
df.groupby('category_new')[['customer_total_spendeing']].sum()

              customer_total_spendeing
category_new
budget                     86336483.86
premium                    73296605.25
regular                    91872705.14

Who their most valuable customers are/Which segment generates the most revenue?
Regular segment creates the most revenue



                                        ANS NUMBER 2 STARTS FROM HERE

In [102]:
df['year'] = df['invoice_date'].dt.year

In [103]:
df['month'] = df['invoice_date'].dt.month

In [106]:
year_2023 = df[df['invoice_date'].dt.year == 2023]
year_2023

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall,customer_total_spendeing,year,month
19,I992454,C196845,Male,24,Toys,4,143.36,Cash,2023-03-07,Cevahir AVM,573.44,2023,3
20,I183746,C220180,Male,23,Clothing,1,300.08,Credit Card,2023-02-15,Emaar Square Mall,300.08,2023,2
35,I339732,C276887,Male,68,Food & Beverage,1,5.23,Credit Card,2023-01-04,Emaar Square Mall,5.23,2023,1
46,I267193,C317818,Female,19,Cosmetics,3,121.98,Credit Card,2023-01-12,Mall of Istanbul,365.94,2023,1
51,I202367,C317478,Female,41,Books,3,45.45,Cash,2023-02-24,Istinye Park,136.35,2023,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
99429,I208840,C219131,Female,58,Toys,1,35.84,Credit Card,2023-02-18,Istinye Park,35.84,2023,2
99441,I203187,C235554,Male,38,Food & Beverage,4,20.92,Cash,2023-03-02,Zorlu Center,83.68,2023,3
99446,I327966,C107209,Female,32,Food & Beverage,1,5.23,Cash,2023-02-05,Metropol AVM,5.23,2023,2
99449,I134399,C953724,Male,65,Clothing,1,300.08,Cash,2023-01-01,Kanyon,300.08,2023,1
99450,I170504,C226974,Female,28,Books,1,15.15,Cash,2023-02-28,Zorlu Center,15.15,2023,2

In [111]:
highest_monthly_sales = year_2023.groupby('month')[['customer_total_spendeing']].sum()
highest_monthly_sales.idxmax()

customer_total_spendeing    2
dtype: int32

Which month has the highest sales for the year 2023?
Month 2 has the highest monthly sales



                                        ANS NUMBER 3 STARTS FROM HERE

In [112]:
df['customer_total_spendeing']

0         7502.00
1         5401.53
2          300.08
3        15004.25
4          242.40
           ...
99452      293.25
99453       20.92
99454       20.92
99455    16800.00
99456      105.57
Name: customer_total_spendeing, Length: 99457, dtype: float64

In [113]:
df['month'] = df['invoice_date'].dt.month

In [114]:
df['day'] = df['invoice_date'].dt.day

In [129]:
highest_monthly_sales = year_2023.groupby('month')[['customer_total_spendeing']].sum()
highest_monthly_sales.idxmax()

customer_total_spendeing    2
dtype: int32

In [130]:
day = df.groupby('day')[['customer_total_spendeing']].sum()
day.idxmax()

customer_total_spendeing    6
dtype: int32

The most sales in a month was in 2nd Month and
the most sales in a day was in 6th day so now lets compare the values

In [128]:
highest_monthly_sales = year_2023.groupby('month')[['customer_total_spendeing']].sum()
highest_monthly_sales.head(2)

       customer_total_spendeing
month
1                    9485599.83
2                    9508662.96

The value of the 2nd month is 9508662.96

In [132]:
day = df.groupby('day')[['customer_total_spendeing']].sum()
day.head(6)

     customer_total_spendeing
day
1                  8251595.34
2                  8477894.32
3                  8672458.43
4                  8694447.93
5                  8594929.99
6                  8934732.76

The value of the 6th day is 8934732.76
Therefore we can clearly see month has the greater sales by values



                                        ANS NUMBER 4 STARTS FROM HERE

In [134]:
df.head(2)

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall,customer_total_spendeing,year,month,day
0,I138884,C241288,Female,28,Clothing,5,1500.40,Credit Card,2022-08-05,Kanyon,7502.00,2022,8,5
1,I317333,C111565,Male,21,Shoes,3,1800.51,Debit Card,2021-12-12,Forum Istanbul,5401.53,2021,12,12

In [154]:
df['category'].value_counts(ascending = False)

category
Clothing           34487
Cosmetics          15097
Food & Beverage    14776
Toys               10087
Shoes              10034
Souvenir            4999
Technology          4996
Books               4981
Name: count, dtype: int64

Clothing category has the most number of sales.



                                        ANS NUMBER 5 STARTS FROM HERE

In [160]:
customer = df.groupby('customer_id')['customer_total_spendeing'].sum()
customer

customer_id
C100004    7502.00
C100005    2400.68
C100006     322.56
C100012     130.75
C100019      35.84
            ...
C999886      47.07
C999910     136.35
C999974    7502.00
C999976     322.56
C999995    1200.32
Name: customer_total_spendeing, Length: 99457, dtype: float64

In [162]:
df['customer'] = df['customer_total_spendeing'].apply(categoryfx)

In [166]:
df.groupby('customer')['customer_total_spendeing'].sum().sort_values(ascending = False)

customer
regular    91872705.14
budget     86336483.86
premium    73296605.25
Name: customer_total_spendeing, dtype: float64

regular segment customers contribute to the most revenue



                                        ANS NUMBER 6 STARTS FROM HERE

In [167]:
def agefx(x):
    if x < 26:
        return('Young Adults')
    elif x < 36:
        return('Early Professionals')
    elif x < 46:
        return('Mid age Adults')
    elif x < 56:
        return('Experienced Adults')
    else:
        return('Senior Customers')
df['age_new'] = df['age'].apply(agefx)

In [170]:
df.groupby('age_new')['customer_total_spendeing'].sum().sort_values(ascending = False)

age_new
Senior Customers       67103884.89
Mid age Adults         50184235.79
Experienced Adults     48219742.64
Early Professionals    47879659.58
Young Adults           38118271.35
Name: customer_total_spendeing, dtype: float64

Senior Customers age group of customers spends more



                                        ANS NUMBER 7 STARTS FROM HERE

In [171]:
df['customer'] = df['customer_total_spendeing'].apply(categoryfx)

In [174]:
df['customer'].unique()

array(['regular', 'budget', 'premium'], dtype=object)

In [175]:
df.head(2)

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall,customer_total_spendeing,year,month,day,category_new,customer_segment,customer,age_new
0,I138884,C241288,Female,28,Clothing,5,1500.40,Credit Card,2022-08-05,Kanyon,7502.00,2022,8,5,regular,regular,regular,Early Professionals
1,I317333,C111565,Male,21,Shoes,3,1800.51,Debit Card,2021-12-12,Forum Istanbul,5401.53,2021,12,12,regular,regular,regular,Young Adults

In [176]:
premium_customer = df[df['customer'] == 'premium']
premium_customer

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall,customer_total_spendeing,year,month,day,category_new,customer_segment,customer,age_new
3,I173702,C988172,Female,66,Shoes,5,3000.85,Credit Card,2021-05-16,Metropol AVM,15004.25,2021,5,16,premium,premium,premium,Senior Customers
15,I688768,C362288,Male,24,Shoes,5,3000.85,Credit Card,2021-11-07,Viaport Outlet,15004.25,2021,11,7,premium,premium,premium,Young Adults
23,I252275,C313348,Male,44,Technology,5,5250.00,Cash,2021-10-26,Kanyon,26250.00,2021,10,26,premium,premium,premium,Mid age Adults
53,I160777,C626042,Female,43,Technology,4,4200.00,Cash,2022-02-22,Metrocity,16800.00,2022,2,22,premium,premium,premium,Mid age Adults
69,I883721,C236859,Female,44,Technology,5,5250.00,Credit Card,2021-11-19,Mall of Istanbul,26250.00,2021,11,19,premium,premium,premium,Mid age Adults
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99288,I173891,C331888,Female,30,Shoes,5,3000.85,Credit Card,2022-10-21,Metropol AVM,15004.25,2022,10,21,premium,premium,premium,Early Professionals
99304,I569860,C340538,Female,22,Shoes,5,3000.85,Cash,2022-06-14,Viaport Outlet,15004.25,2022,6,14,premium,premium,premium,Young Adults
99307,I327672,C200968,Female,54,Shoes,5,3000.85,Cash,2021-11-23,Mall of Istanbul,15004.25,2021,11,23,premium,premium,premium,Experienced Adults
99332,I206967,C232954,Female,53,Shoes,5,3000.85,Credit Card,2022-03-13,Metrocity,15004.25,2022,3,13,premium,premium,premium,Experienced Adults
99455,I702964,C800631,Male,56,Technology,4,4200.00,Cash,2021-03-16,Istinye Park,16800.00,2021,3,16,premium,premium,premium,Senior Customers

In [178]:
premium_customer.groupby('category')['customer_total_spendeing'].sum().sort_values(ascending = False)

category
Technology    43093050.00
Shoes         30203555.25
Name: customer_total_spendeing, dtype: float64

Technology products are mostly purchased by the high value customers

According to my business analysis this can be done to improve more
Focus on Regular Customers
Offer them customized offers, discounts, and loyalty rewards to spend more because they bring in the highest amount of revenue.
Upgrade Budget Customers
Promote using spend more, save more offers (e.g. 10% off over a threshold) and simple loyalty programs to boost their average purchase value.
Retain Premium Customers
Provision of VIP services, discounts and prior access to ensure they are kept loyal.
Improve Seasonal Sales
Conduct promotions during low sale seasons to ensure that incomes do not decrease during the low sale seasons.
Prioritize Top-Selling Categories
Target high demand products (such as technology products) by making them available and more promoted.